services:
  catalog:
    build: ./catalog
    ports:
      - "8084:8084"

  plotter:
    build: ./data_analysis
    depends_on:
      - catalog
    ports:
      - "1400:1400"
    
  
  storer:
    build: ./dataHandler
    depends_on:
      - catalog

  publisher0:
    build: ./publisher0
    depends_on:
      - catalog

  
  telegrambot:
    build: ./telegram
    depends_on:
      - catalog
    ports:
      - "1402:1402"

  statistics:
    build: ./dataStatistics
    depends_on:
      - catalog
    ports:
      - "8050:8050"
