services:
  catalog:
    build: ./catalog
    ports:
      - "8084:8084"

  plotter:
    build: ./dataPlotter
    depends_on:
      - catalog
    ports:
      - "1400:1400"
    

  alerter:
    build: ./dataAlerter
    depends_on:
      - catalog

  connector:
    build: ./influxConnector
    depends_on:
      - catalog

  device0:
    build: ./device0
    depends_on:
      - catalog

  device1:
    build: ./device1
    depends_on:
      - catalog

  device2:
    build: ./device2
    depends_on:
      - catalog
    
  device3:
    build: ./device3
    depends_on:
      - catalog

  telegrambot:
    build: ./telegram
    depends_on:
      - catalog
      - statistics
      - plotter
      - connector
    ports:
      - "1402:1402"

  statistics:
    build: ./dataStatistics
    depends_on:
      - catalog
    ports:
      - "8050:8050"
